name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches: [main]
  pull_request:
    paths:
      - 'backend/**'
    branches: [main]

jobs:
  install-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache backend dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            backend/node_modules
          key: ${{ runner.os }}-node-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-backend-

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

  test-backend:
    needs: install-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run backend tests
        working-directory: backend
        run: npm test

  lint-backend:
    needs: install-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run backend lint
        working-directory: backend
        run: npm run lint

  docker-build-backend:
    needs: lint-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend Docker image with BuildKit
        run: |
          DOCKER_BUILDKIT=1 docker build -t my-backend:latest -f backend/Dockerfile backend/
